packages:
  - "apps/*"
  - "packages/*"

allowBuilds:
  esbuild: true
  lightningcss: true
  unrs-resolver: true

autoInstallPeers: true
minimumReleaseAge: 0
sharedWorkspaceLockfile: true
strictPeerDependencies: false
